apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
  labels:
    app: django
spec:
  schedule: "0 0 1 * *"
  startingDeadlineSeconds: 15
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
          - name: django-clearsessions
            image: melei/django_app:0.0.1
            imagePullPolicy: IfNotPresent
            command: ["python", "manage.py", "clearsessions"]
            envFrom:
              - configMapRef:
                  name: dj-config
          restartPolicy: Never