apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dj-deployment
  namespace: edu-sleepy-engelbart
  labels:
    app: django
  annotations:
    configmap.reloader.stakater.com/reload: "dj-config"
spec:
  replicas: 3
  selector:
    matchLabels:
      project: django_k8s
  template:
    metadata:
      labels:
        project: django_k8s
    spec:
      containers:
      - name: dj-web
        image: melei/django_app
        imagePullPolicy: IfNotPresent
        envFrom:  
          - configMapRef:
              name: dj-config
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: edu-sleepy-engelbart
spec:
  selector:
    project: django_k8s
  ports:
    - name: django-port
      nodePort: 30031
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

